import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "../app/lib/registry";
import Container from "@mui/material/Container";
import UtilBar from "../../Components/UtilBar";
import MainNav from "../../Components/MainNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          {" "}
          <Container maxWidth="xl">
            <UtilBar />
            <MainNav />
            {children}
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
